name: CI Pipeline

on:
 push:
   branches:
     - main
     - develop
   paths:
     - 'src/**' # it will trigger if the changes happen in 'src/'

 pull_request:
   branches:
     - main
     - develop
   types:
     - opened
     - synchronize  # iT will run when the PR will updated with new commits.

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: Run build
       uses: Echo " Running the build step"

 test:
   runs-on: ubuntu-latest
   needs: build
   if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # It will only runs on main branch pushes.
   steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: Run Tests
       uses: echo " Running tests"
   
     
