name: CI

on:
  push:
    branches:
      - feature_branch1
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      run-name: production
      defaults: https://api.example.com

