name: Matrix

run-name: DEBUG | ${{inputs.debug}}

on:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
    

jobs:
 matrix-echo:
  runs-on: ${{matrix.os}}
  strategy:
   fail-fast: true
   matrix:
    os: 
     - ubuntu-latest
     - windows-latest
    node-version: [v22, v21]
  steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
         node-version: ${{matrix.node-version}}
      - name: Perform test
        run: echo 'Display ${{matrix.os}} and ${{matrix.node-version}}'
